ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

cbdb:
  # pkg_name: "cloudberrydb" # for 1.5.x
  pkg_name: "cloudberry-db" # for 1.6.x
  cluster_name: jack-kr-cbdb
  base_dir: "/usr/local"
  admin_user: "gpadmin"
  admin_passwd: "changeme"
  admin_home_dir: "/home/gpadmin"
  coordinator_data_dir: "/data/coordinator/gpseg-1"
  data_dir: "/data"
  major_version: 1
  minor_version: 6
  patch_version: 0
  build_version: 1
  os_name: 'el9'
  # os_name: 'rl9'
  arch_name: 'x86_64'
  binary_type: 'rpm'
  number_segments: 4
  mirror_enable: true
  spread_mirrors: ""
  initdb_single: False
  initdb_with_standby: True
  seg_serialized_install: False
  domain: "jtest.pivotal.io"
  repo_url: ""
  download_url: ""
  download: false
  base_path: /root
  host_num: "{{ groups['all'] | length }}"
  cgroup: v1
  metric_major_version: 6
  metric_minor_version: 26.0
  metric_build_version:
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"
  client:
    net:
      type: "virtual"              # Or Physical
      cores: 1
      ipaddr0: "192.168.0.6"
      ipaddr1: "192.168.1.6"
      ipaddr2: "192.168.2.6"
  ext_storage:
    net:
      ipaddr0: "192.168.0."
      ipaddr1: "192.168.1."


jdk:
  oss:
    install: true
    jvm_home: "/usr/lib/jvm"
    major_version: 1
    minor_version: 8
    patch_version: 0
    # 1.8.0
    # 11.0.4
    # 17.0.2
  oracle:
    install: false
    jvm_home: "/usr/lib/jvm"
    major_version: 13
    minor_version: 0
    patch_version: 2
    download: false


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"


#ssl:
#  dir: "/data/coordinator/gpseg-1"
#  days: 3660
#  country: "KR"
#  state: "Seoul"
#  location: "Guro"
#  organization: "Pivotal"
#  organization_unit: "Global Support Service"
#  common_name: "jtest.pivotal.io"
#  email: "jomoon@pivotal.io"

