---
- name: Restart System
  shell: ( /bin/sleep 5 ; /sbin/shutdown -r now "Ansible updates triggered" ) &
  async: 30
  poll: 0
  ignore_errors: true


- name: Waiting for Server to Come Back after Reboot
  local_action: wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=started delay=10 timeout=300 connect_timeout=300 search_regex=OpenSSH
  become: no


- name: Reload Sysctl
  shell: |
    /sbin/sysctl -p
    /sbin/sysctl -p /etc/sysctl.conf


- name: Start CloudBerry Database
  become_user: gpadmin
  shell: ( . {{ cbdb.base_dir }}/{{ cbdb.pkg_name }}/greenplum_path.sh && gpstart -a )
  async: 60
  poll: 5


- name: Stop CloudBerry Database
  become_user: gpadmin
  shell: ( . {{ cbdb.base_dir }}/{{ cbdb.pkg_name }}/greenplum_path.sh && gpstop -a )
  async: 60
  poll: 5


- name: Restart CloudBerry Database
  become_user: gpadmin
  shell: ( . {{ cbdb.base_dir }}/{{ cbdb.pkg_name }}/greenplum_path.sh && gpstop -ra )
  async: 60
  poll: 5


- name: Reload SSHd
  service:
    name: sshd
    state: reloaded


- name: Reload Systemd-Logind
  service:
    name: systemd-logind
    state: restarted


- name: Start Firewalld
  service: name=firewalld state=started enabled=yes


- name: Stop Firewalld
  service: name=firewalld state=stopped enabled=no


- name: Restart Firewalld
  service: name=firewalld state=restarted enabled=yes


- name: Start IPtables
  service: name=iptables state=started enabled=yes


- name: Stop IPtables
  service: name=iptables state=stopped enabled=no


- name: Restart IPtables
  service: name=iptables state=restarted enabled=yes


- name: Enable SELinux
  selinux: policy=targeted state=enforcing


- name: Disable SELinux
  selinux: state=disabled


