package_download_path : "/tmp"
freeipa:
  admin_user: admin
  admin_passwd: changeme
  client_domain: {{ cbdb.domain }}
  client_server: lab.{{ cbdb.domain }}
  client_ipaddr: 192.168.2.101
  client_realm: JTEST.FUTURFUSION.IO
  client_fqdn: "{{ hostvars[groups['master'][0]].ansible_hostname }}"
  client_extra_args: [ '--kinit-attempts=3', '--mkhomedir']
  ldap:
    database: ldap_testdb
    server: "192.168.2.101"
    cn: "cn=users,cn=accounts"
    dn: "dc=jtest,dc=futurfusion,dc=io"
    users:
      - { username: jmoon, passwd: changeme, first_name: Jack, last_name: Moon }
      - { username: rmoon, passwd: changeme, first_name: Rose, last_name: Moon }
  kerberos:
    database: krb5_testdb
    client_principal: admin
    client_password: changeme
    client_keytab: /etc/krb5.keytab
    client_cbdb_keytab: /home/gpadmin/cbdb-kerberos.keytab
    client_keytab_fullpath: /etc/krb5.keytab
    users:
      - { username: gpuser,  passwd: changeme, first_name: GPAdmin , last_name: Moon }

ssl:
  dir: "{{ cbdb.coordinator_data_dir }}"
  days: 3660
  country: "KR"
  state: "Seoul"
  location: "Guro"
  organization: "FuturFusion"
  organization_unit: "Global Support Service"
  common_name: "{{ cbdb.domain }}"
  email: "jomoon@futurfusion.io"

