#
- hosts: all
  become: true
  gather_facts: yes
  roles:
    - { role: cbdb }                 # Need to check if get_facts: true is required
#    - { role: init-hosts }
#    - { role: pxf }
#    - { role: init-hosts }


#- hosts: rk8-master,rk8-slave
#  become: true
#  become_user: gpadmin
#  roles:
#    - { role: gpcc }


#- hosts: rk8-master
#  become: true
#  gather_facts: true
#  roles:
#    - { role: pgbouncer }


#- hosts: rk9-minio
#  become: true
#  gather_facts: true
#  vars:
#    use_nginx: true
#    minio_download: false
#  roles:
#    - { role: minio }                 # Need to check if get_facts: true is required
