---
- name: Check if Any Version of CloudBerry MPP Database is Already Installed
  stat: path={{ cbdb.base_dir }}/{{ link_path }}
  register: check_cbdb_link


- name: Check if the CloudBerry MPP Database Version is Already Installed
  stat: path={{ cbdb.base_dir }}/{{ install_path }}
  register: check_cbdb_dir


- name: Sanity Check for {{ cbdb.base_dir }}/{{ cbdb.pkg_name }}
  fail: msg="{{ cbdb.base_dir }}/cloudberry-db or {{ cbdb.base_dir }}/{{ install_path }} Already Exists!"
  when: check_cbdb_link.stat.exists == True or check_cbdb_link.stat.exists == True


- name: Set Default Values for Run Mode Variables
  set_fact:
    cbdb_install: False
    cbdb_linkchange: False


- name: Identify CloudBerry MPP Database Installation
  set_fact:
    cbdb_install: True
  when: check_cbdb_dir.stat.exists != True and check_cbdb_link.stat.exists != True


# If the link points to a different existing directory, it's a link change
- name: Identify CloudBerry MPP Database Linkchange
  set_fact:
    cbdb_linkchange: True
  when: check_cbdb_link.stat.exists != True


- name: CloudBerry MPP Database Installation
  debug: msg="New CloudBerry MPP Database installation"
  when: cbdb_install == True


- name: CloudBerry MPP Database Link Change
  debug: msg="Changing link to CloudBerry MPP Database version"
  when: cbdb_linkchange == True


- name: CloudBerry MPP Database - Nothing to do
  debug: msg="Nothing to do (no installation/upgrade required)"
  when: cbdb_install == False and cbdb_linkchange == False


- debug: msg={{ cbdb_install }}
- debug: msg={{ cbdb_linkchange }}
- debug: msg={{ cbdb_install }}
- debug: msg={{ install_path }}
- debug: msg={{ link_path }}

