---
- name: Check OS ( CloudBerry Database )
  fail: msg="{{ ansible_distribution }} is not Supported for This Ansible Playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'


- name: Set Facts for CloudBerry Database
  import_tasks: set-cbdb-facts.yml
  tags:
    - install
    - uninstall
    - prepare


- name: Check if CloudBerry Database is Installed Already
  import_tasks: check-cbdb-installed.yml
  tags: prepare, install, uninstall, deploy, init, enable


- name: Prepare OS Parameters
  import_tasks: prepare-os-parameters.yml
  tags: prepare


- name: Install CloudBerry Database Software Binary
  import_tasks: install-cbdb.yml
  tags: install, deploy, init
  when: ( db is defined and db == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Initialize CloudBerry Database
  import_tasks: init-cbdb.yml
  tags: install, init, deploy
  when: ( db is defined and db == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Add CloudBerry Standby Master Database
  import_tasks: init-stadnby-cbdb.yml
  tags: install, init, deploy
  when: ( standby is defined and standby == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Enable SSL
  import_tasks: enable-ssl.yml
  tags: install, enable
  when: ( tls is defined and tls == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Enable LDAP Authentication
  import_tasks: enable-ldap.yml
  tags: install, enable
  when: ( ldap is defined and ldap == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Enable Resource Group
  import_tasks: enable-resource-group.yml
  tags: install, enable
  when: ( rg is defined and rg == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Enable Kerberos Authentication
  import_tasks: enable-kerberos.yml
  tags: install, enable
  when: ( krb5 is defined and krb5 == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Finalize CloudBerry Database
  import_tasks: finalize-cbdb.yml
  tags: install, deploye
  when: ( db is defined and db == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Uninstall LDAP Authentication
  import_tasks: uninstall-ldap.yml
  tags: uninstall, destroy
  when: ( ldap is defined and ldap == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Uninstall Kerberos Authentication
  import_tasks: uninstall-kerberos.yml
  tags: uninstall, destroy
  when: ( krb5 is defined and krb5 == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Disable Resource Group
  import_tasks: disable-resource-group.yml
  tags: uninstall, disable
  when: ( rg is defined and rg == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Uninstall CloudBerry Database
  import_tasks: uninstall.yml
  tags: uninstall, destroy
  when: ( db is defined and db == true ) or ( cbdb_all is defined and cbdb_all == true )


- name: Upgrade CloudBerry Database
  import_tasks: upgrade.yml
  tags: upgrade
  when: ( db is defined and db == true ) or ( cbdb_all is defined and cbdb_all == true )

