###########################################################
# Basic OS Setup
#
- name: Add GPAdmin Group
  group:
    name: gpadmin
    state: present


# Do not create ssh keys since this conflicts somehow with gpssh-exkeys
- name: Add GPAdmin User
  user:
    name: gpadmin
    password: "{{ 'changeme' | password_hash('sha512') }}"
    comment: 'CloudBerry Administrator'
    createhome: yes
    shell: /bin/bash
    generate_ssh_key: no
    groups: gpadmin
    append: yes
    state: present
  changed_when: False


- name: Fix Ownership for {{ cbdb.base_dir }}
  file: path={{ cbdb.base_dir }} state=directory mode=0755 owner=gpadmin group=gpadmin


- name: Stop and Disable Iptables for RHEL / CentOS 6.x and lower versions
  service: name=iptables state=stopped enabled=no
  changed_when: False
  when: ( ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' ) and hostvars[inventory_hostname].ansible_distribution_major_version|int <= 6


- name: Stop and Disable firewalld for RHEL / CentOS / Rocky LInux 7.x and higher versions
  service: name=firewalld state=stopped enabled=no
  changed_when: False
  when: ( ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' ) and  hostvars[inventory_hostname].ansible_distribution_major_version|int > 7


- name: Stop and Disable ufw, ebtables for Ubuntu / Debian Linux
  service: name={{ item }} state=stopped enabled=no
  changed_when: False
  ignore_errors: true
  with_items:
    - ufw
    - ebtables
    - firewalld
    - snapd
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'


- name: Disable SELinux
  selinux: state=disabled
  notify:
    - Restart system
    - Waiting for Server to Come Back after Reboot


- name: Modify /etc/systemd/logingd.conf to Not Remove
  lineinfile:
    dest: /etc/systemd/logind.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { regexp: '^#RemoveIPC=', line: 'RemoveIPC=no', state: present }
  notify:
    - Reload Systemd-Logind


- name: Modify /etc/sysctl.d/98-sysctl-cbdb.conf
  lineinfile:
    dest: /etc/sysctl.d/98-sysctl-cbdb.conf
    regexp: "^{{ item.param }}"
    line: "{{ item.param }} = {{ item.value }}"
    state: "{{ item.state }}"
    create: yes
  with_items: "{{ common_cbdb_kernel_parameters }}"
  notify:
    - Reload Sysctl


- name: Modify /etc/sysctl.d/98-sysctl-cbdb.conf
  lineinfile:
    dest: /etc/sysctl.d/98-sysctl-cbdb.conf
    regexp: "^{{ item.param }}"
    line: "{{ item.param }} = {{ item.value }}"
    state: "{{ item.state }}"
    create: yes
  with_items: "{{ rhel7_cbdb_kernel_parameters }}"
  notify:
    - Reload Sysctl
  when: ( ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' ) and hostvars[inventory_hostname].ansible_distribution_major_version|int <= 7


- name: Modify /etc/ssh/sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin yes', state: present }
  notify:
    - Reload SSHd


- name: Security limits
  copy: src=security_limits.conf dest=/etc/security/limits.d/95-cbdb.conf
  notify:
    - Restart System
    - Waiting for Server to Come Back after Reboot


# Need to add XFS options
# Need to check I/O scheduler

- meta: flush_handlers

