---
- name: Check OS ( OSS CloudBerry Database )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'


- name: Install OSS CloudBerry Database
  import_tasks: install.yml
  tags: install


- name: Uninstall OSS CloudBerry Database
  import_tasks: uninstall.yml
  tags: uninstall


- name: Upgrade OSS CloudBerry Database
  import_tasks: upgrade.yml
  tags: upgrade

