---
- name: Check OS ( Firewalld )
  fail: msg="Not a Red Hat based system!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Configure firewalld ruleset for CloudBerry on {{ ansible_distribution }}
  import_tasks: install.yml
  tags: install


- name: Clean firewalld ruleset for CloudBerry on {{ ansible_distribution }}
  import_tasks: uninstall.yml
  tags: uninstall

