---
- name: Check if the PXF Cluster is Running on Each Segment Hosts
  become_user: "{{ cbdb.admin_user }}"
  shell: ( source /usr/local/{{ cbdb.pkg_name }}/greenplum_path.sh && export PXF_BASE=/usr/local/{{ cbdb_pxf_version }} && /usr/local/{{ cbdb_pxf_version }}/bin/pxf cluster status )
  ignore_errors: yes
  register: pxf_running_checked
  when: inventory_hostname in groups['master']


- name: Stop PXF Cluster Running on Each Segment Hosts
  become_user: "{{ cbdb.admin_user }}"
  shell: ( source /usr/local/{{ cbdb.pkg_name }}/greenplum_path.sh && export PXF_BASE=/usr/local/{{ cbdb_pxf_version }} && /usr/local/{{ cbdb_pxf_version }}/bin/pxf cluster stop )
  ignore_errors: yes
  when: inventory_hostname in groups['master'] and 'PXF is running on' in pxf_running_checked.stdout

