---
- name: Detect Google Cloud
  stat: path=/etc/yum.repos.d/google-cloud.repo
  register: google_cloud_detect


- name: Register Google Cloud
  set_fact:
    google_cloud: true
  when: google_cloud_detect.stat.exists


- name: Check if any version of CloudBerry Database is already installed
  stat: path={{ cbdb.base_dir }}/{{ cbdb.pkg_name }}
  register: cbdb_installed


- name: Check if the CloudBerry Database version is already installed
  stat: path={{ cbdb.base_dir }}/{{ cbdb.pkg_name }}-{{ cbdb.major_version }}.{{ cbdb.minor_version }}
  register: cbdb_version_installed


- name: Sanity check for {{ cbdb.base_dir }}/{{ cbdb.pkg_name }}
  fail: msg="{{ cbdb.base_dir }}/{{ cbdb.pkg_name }} is supposed to be a symlink!"
  when: cbdb_installed.stat.exists == True and cbdb_installed.stat.islnk != True


- name: Shutdown database
  become_user: gpadmin
  shell: ( . {{ cbdb.base_dir }}/{{ cbdb.pkg_name }}/greenplum_path.sh && gpstop -a )
  async: 60
  poll: 5
  when:
   - inventory_hostname in groups['master']
   - cbdb_installed.stat.exists == True and cbdb_version_installed.stat.exists == True


- name: Copy CloudBerry Database {{ cbdb.major_version }} {{ cbdb.binary_type }} file
  copy: src={{ binary_installer_file }}.rpm dest=/home/gpadmin/{{ binary_installer_file }}.rpm mode=0644 owner=gpadmin group=gpadmin
  when:
    - cbdb_binary_type == 'rpm'


- name: Upgrade CloudBerry Database software in {{ cbdb_base_dir }}
  yum:
    name: /home/gpadmin/{{ binary_installer_file }}.rpm
    state: latest
  async: 60
  poll: 5
  when:
    - cbdb_installed.stat.exists == True and cbdb_version_installed.stat.exists == True
    - cbdb_binary_type == 'rpm'


- name: Update the permissions for the new installation
  become_user: gpadmin
  file:
    path: "{{ cbdb.base_dir }}/{{ cbdb.pkg_name }}-{{ cbdb.major_version }}.{{ cbdb.minor_version }}.{{ cbdb.build_version }}"
    owner: gpadmin
    group: gpadmin
    recurse: yes


- name: Change the following line in the .bashrc or your chosen profile file
  replace:
    path: /home/gpadmin/.bashrc
    regexp: "^source /usr/local/{{ cbdb.pkg_name }}*"
    replace: "^source {{ cbdb.base_dir }}/{{ cbdb.pkg_name }}-{{ cbdb.major_version }}.{{ cbdb.minor_version }}.{{ cbdb.build_version }}"
    backup: yes
# GPHOME=/usr/local/{{ cbdb.pkg_name }}-6.11.1 in /usr/local/{{ cbdb.pkg_name }}/greenplum_path.sh


- name: Remove the link to point to the earily installed version
  become_user: gpadmin
  file:
    path: "{{ cbdb.base_dir }}/{{ cbdb.pkg_name }}"
    owner: gpadmin
    group: gpadmin
    state: absent


- name: Update the link to point to the newly installed version
  file:
    src: "{{ cbdb.base_dir }}/{{ cbdb.pkg_name }}-{{ cbdb.major_version }}.{{ cbdb.minor_version }}.{{ cbdb.build_version }}"
    dest: "{{ cbdb.base_dir }}/{{ cbdb.pkg_name }}"
    state: link


- name: Source the environment file of cbdb
  become_user: gpadmin
  changed_when: False
  shell: ( source /home/gpadmin/.bashrc )
  register: environment_sourced
  when: inventory_hostname in groups['master']


- name: Start CloudBerry Database after upgrade
  become_user: gpadmin
  shell: ( . {{ cbdb.base_dir }}/{{ cbdb.pkg_name }}/greenplum_path.sh && gpstart -a )
  async: 60
  poll: 5
  when: inventory_hostname in groups['master']

